# Generated by Django 4.2.3 on 2023-12-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='email',
        ),
    ]
