# Generated by Django 4.2.3 on 2023-12-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_barbeiro_email_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='type_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='type_cliente',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='type_cliente',
        ),
    ]
