# Generated by Django 4.2.3 on 2023-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_barbeiro_type_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='type_cliente',
            field=models.CharField(choices=[('cli', 'cliente'), ('ger', 'gerente'), ('bar', 'barbeiro')], default='cli', max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='type_cliente',
            field=models.CharField(choices=[('cli', 'cliente'), ('ger', 'gerente'), ('bar', 'barbeiro')], default='cli', max_length=3),
        ),
        migrations.AddField(
            model_name='gerente',
            name='type_cliente',
            field=models.CharField(choices=[('cli', 'cliente'), ('ger', 'gerente'), ('bar', 'barbeiro')], default='cli', max_length=3),
        ),
    ]
