# Generated by Django 4.2.3 on 2023-12-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_barbeiro_type_cliente_cliente_type_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='codigo',
            field=models.CharField(max_length=8),
        ),
    ]
