# Generated by Django 4.2.3 on 2023-12-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_gerente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='img',
            field=models.ImageField(default='avatar_default.png', upload_to='barbeiro/'),
        ),
    ]
