# Generated by Django 5.0 on 2023-12-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_barbeiro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerente',
            name='codigo',
        ),
    ]
