# Generated by Django 4.2.3 on 2023-12-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('horario', models.DateField()),
                ('cpf_gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.gerente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.barbeiro')),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('id_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
            ],
        ),
    ]
