# Generated by Django 4.2.3 on 2023-12-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
