# Generated by Django 4.2.3 on 2023-12-12 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(),
        ),
    ]
