# Generated by Django 5.0 on 2023-12-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_data_alter_agendamento_horario'),
        ('cadastro', '0006_barbeiro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf_gerente',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.barbeiro'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente_Agendamento',
        ),
    ]
