# Generated by Django 5.0 on 2023-12-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_remove_agendamento_cpf_gerente_agendamento_barbeiro_and_more'),
        ('cadastro', '0006_barbeiro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.barbeiro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente'),
        ),
    ]
