# Generated by Django 4.2.3 on 2023-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_alter_agendamento_barbeiro_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
